sudo: required
services:
  - docker

# Look into the client directory for the build context
before_install:
  - docker build -t diode/react-test -f ./client/Dockerfile.dev ./client

# test script should exit with --coverage
script:
  - docker run diode/react-test npm test -- --coverage

after_success:
# Build everything
  - docker build -t diode/multi-client ./client
  - docker build -t diode/multi-nginx ./nginx
  - docker build -t diode/multi-server ./server
  - docker build -t diode/multi-worker ./worker

# Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push these images to docker hub
  - docker push diode/multi-client
  - docker push diode/multi-nginx
  - docker push diode/multi-server
  - docker push diode/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-837134779439
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

